name: Translations
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  quality:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Check translations
        run: |
          wget https://raw.githubusercontent.com/Temeez/scripts/main/python3/test_fluent.py
          python3 test_fluent.py
